blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('create/', views.blog_upload, name='create_post'),
    path('post_detail/<slug:slug>', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
    path('update/<slug:slug>', views.PostUpdate.as_view(), name='post_update'),
    path('delete/<slug:slug>', views.PostDelete.as_view(), name='post_delete'),
]

byteblog/urls.py
from django.contrib import admin
from django.urls import path, include
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
    path('category/<slug:slug>', blog.views.category, name='category'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify

STATUS = ((0, "Draft"), (1, "Published"))


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='blog_likes', blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="category")

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")
    name = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

blog/forms.py
from .models import Comment, Post
from django import forms
from . import models


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic.edit import DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from .models import Post, Category
from .forms import CommentForm, BlogForm
from . import forms


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = "index.html"


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by('-created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request, "post_detail.html", {"post": post, "comments": comments,
                                          "commented": False, "liked": liked, "comment_form": CommentForm()},
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by('-created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request, "post_detail.html", {"post": post, "comments": comments,
                                          "commented": True, "liked": liked, "comment_form": CommentForm()},
        )


def blog_upload(request):

    queryset = Post.objects.all()
    blog_form = BlogForm()
    if request.method == 'POST':
        blog_form = BlogForm(request.POST)

        if blog_form.is_valid():
            form = blog_form.save(commit=False)
            form.author = request.user
            form.post = queryset
            form.save()
            blog_form.save_m2m()
            messages.add_message(request, messages.SUCCESS,
                                 "Form submitted! Waiting approval..")

        else:
            blog_form = BlogForm()

    return render(request, "create_post.html", {"blog_form": blog_form})


def category(request, slug):

    post_category = Post.objects.filter(category__slug=slug).filter(status=1)

    return render(request, 'category.html', {'post_category': post_category, 'category': category})


class PostLike(View):

    def get(self, request, slug, *args, **kwargs):

        post = get_object_or_404(Post, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))

    def post(self, request, slug, *args, **kwargs):

        post = get_object_or_404(Post, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))


class PostUpdate(UpdateView):
    model = Post

    template_name = 'post_update.html'
    form_class = BlogForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        resp = super().form_valid(form)

        self.object.status = 0
        self.object.save()
        messages.success(self.request, 'Form updated! Waiting approval.. ')
        return resp


class PostDelete(DeleteView):
    model = Post

    success_url = reverse_lazy('home')
    template_name = 'post_delete.html'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Byte Blog</title>
</head>

<body class="mx-lg-5 px-lg-5">
    <!--Navigation-->
    <nav class="navbar navbar-expand-lg navbar-expand-md mb-5">
        <div class="container-fluid">
            <ul class="navbar-nav me-auto">
                <a href="{% url 'home' %}" class="nav-link fs-3 navbar-brand text-info"><strong>BYTE</strong>BLOG</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light pt-3" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu bg-body-secondary">
                        {% for category in categories %}
                        <li>

                            <a class="dropdown-item" href="{% url 'category' category.slug %}">{{ category.name }}</a>

                        </li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <div class="dropdown me-2">
                <a class="dropdown-toggle text-light" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ user }}<i class="fa fa-id-card-o px-2 text-info" aria-hidden="true"></i></a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'create_post' %}">Create a post</a></li>
                </ul>
            </div>
            <a href="{% url 'account_logout' %}" class="btn btn-outline-warning" type="button">Logout</a>
            {% else %}
            <a href="{% url 'account_login' %}" class="btn btn-outline-warning" type="button">Login/Register</a>
            {% endif %}
        </div>
    </nav>
    <div class=" text-center">

        {% for message in messages %}
        <h2 class="text-warning {{ message.tags }} alert alert-dismissible fade show" role="alert" id="msg">
            {{ message | safe }}</h2>
        {% endfor %}

    </div>
    <main>
        {% block content %}
        <!--main posts body-->
        {% endblock content %}
    </main>
    <footer class="fixed-bottom socials">
        <div class="card text-center">
            <div class="card-header bg-secondary text-light btn" data-bs-toggle="collapse" href="#collapseExample"
                role="button" aria-expanded="false" aria-controls="collapseExample">Socials</div>
            <div class="card-body bg-secondary collapse" id="collapseExample">
                <a href="https://twitter.com/" class="pe-lg-5 pe-3" target="_blank"><i class="fa fa-twitter"></i></a>
                <a href="https://en-gb.facebook.com/" class="pe-lg-5 ps-lg-5 pe-3 ps-3" target="_blank"><i
                        class="fa fa-facebook"></i></a>
                <a href="https://www.instagram.com/" class="pe-lg-5 ps-lg-5 pe-3 ps-3" target="_blank"><i
                        class="fa fa-instagram"></i></a>
                <a href="https://uk.linkedin.com/" class="ps-lg-5 ps-3" target="_blank"><i
                        class="fa fa-linkedin"></i></a>
            </div>
        </div>
    </footer>
</body>
<script>
    setTimeout(function () {
        let messeges = document.getElementById("msg");
        let alert = new bootstrap.Alert(messeges);
        alert.close();
        window.location.replace("{% url 'home' %}");
    }, 2000);  
</script>
<script src="https://kit.fontawesome.com/13074e55fe.js" crossorigin="anonymous"></script>

</html>

templates/category.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- For Blog Entries -->
        <div class="col-12 left mb-5">
            <div class="row">
                {% for post in post_category %}
                <div class="col-md-3">
                    <div class="card mb-3">
                        <div class="card-body bg-secondary">
                            <div>
                                <!-- Main image for the post -->
                                {% if post.category.slug == 'code' %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020844/Code_sckmh5.jpg">
                                {% elif post.category.slug == 'apps' %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020880/Apps_ummulq.jpg">
                                {% else %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020796/Games_ah8sad.jpg">
                                {% endif %}
                                <div>
                                    <!-- Posts author, created date and likes-->
                                    <p class="">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug  %}" class="text-warning">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart heart"></i>
                                {{ post.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/create_post.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-info text-center">Create a Post</h2>

<div class="col-md-8 mx-auto text-center d-flex justify-content-center">

    <form class="p-3 col-md-8 card bg-secondary text-info border-white" method="POST" enctype="multipart/form-data">

        {{ blog_form }}
        {% csrf_token %}

        <button class="btn btn-outline-warning" type="submit">Submit</button>
    </form>
</div>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% load cloudinary %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- For Blog Entries -->
        <div class="col-12 left mb-5">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-3">
                    <div class="card mb-3">
                        <div class="card-body bg-secondary">
                            <div>
                                <!-- Main image for the post -->
                                {% if post.category.slug == 'code' %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020844/Code_sckmh5.jpg">
                                {% elif post.category.slug == 'apps' %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020880/Apps_ummulq.jpg">
                                {% else %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020796/Games_ah8sad.jpg">
                                {% endif %}
                                <div>
                                    <!-- Posts author, created date and likes-->
                                    <p class="">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug  %}" class="text-warning">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart heart"></i>
                                {{ post.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:4 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/post_delete.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-center">Delete Post?</h1>
<h2 class="text-center text-info mt-5">{{ post.title }}</h2>

<form class="d-flex justify-content-center" method="POST">

  {% csrf_token %}
  
  <button class="btn btn-outline-danger p-3 mt-5" type="submit" value="Confirm">Delete</button>
</form>

{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<!-- Posts content -->
<div class="container">
    <div class="row">
        <div class="col-md-3 p-3">
            {% if post.category.slug == 'code' %}
            <img class="card-img-top"
                src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020844/Code_sckmh5.jpg">
            {% elif post.category.slug == 'apps' %}
            <img class="card-img-top"
                src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020880/Apps_ummulq.jpg">
            {% else %}
            <img class="card-img-top"
                src="https://res.cloudinary.com/dqhxfqvdo/image/upload/v1689020796/Games_ah8sad.jpg">
            {% endif %}
        </div>
        <div class="col-md-5">
            <h2 class="text-warning">{{ post.title }}</h2>
            <p class="text-light">{{ post.author }} | {{ post.created_on }} | {{ post.category }}</p>
            <div>
                {% if user.is_authenticated %}
                {% if user.id == post.author.id %}
                <a class="btn btn-outline-danger" href="{% url 'post_delete' post.slug %}">Delete</a>
                <a class="btn btn-outline-warning" href="{% url 'post_update' post.slug %}">Edit</a>
                {% endif %}
                <form class="d-inline" action="{% url 'post_like' post.slug %}">
                    {% csrf_token %}
                    {% if liked %}
                    <button type="submit" class="btn" name="blogpost_id" value="{{ post.slug }}"><i
                            class="fas fa-heart heart"></i></button>
                    {% else %}
                    <button type="submit" class="btn" name="blogpost_id" value="{{ post.slug }}"><i
                            class="far fa-heart heart"></i></button>
                    {% endif %}
                </form>
                {% else %}
                <strong class="text-info"><i class="far fa-heart heart p-1"></i></strong>
                {% endif %}
                <strong class="text-light">{{ post.number_of_likes }}</strong>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 --bs-dark-border-subtle">
            <h5 class="text-light p-4">{{ post.content|safe }}</h5>
            <hr class="text-warning">
        </div>
        <div class="row">
            <div class="col-1">
                {% with comments.count as total_comments %}
                <strong class="text-light"><i class="far fa-comments p-1 text-info"></i>{{ total_comments }}</strong>
                {% endwith %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <hr class="text-warning">
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-md-8 card  bg-secondary">
                    <h4 class="text-warning">Comments:</h4>
                    <div class="card-body">
                        {% for comment in comments %}
                        <div>
                            <p class="text-info">
                                {{ comment.name }}
                                <span class="">
                                    {{ comment.created_on }}
                                </span>
                            </p>
                            {{ comment.body | linebreaks }}
                            <hr class="text-warning">
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-4 mb-5 ">
                    {% if commented %}
                    <div class="alert alert-success">
                        Your comment is awaiting approval
                    </div>
                    {% else %}

                    {% if user.is_authenticated %}

                    <h3 class="text-warning">Comment:</h3>
                    <p>Post by: {{ user.username }}</p>
                    <form method="post">
                        {{ comment_form | crispy }}
                        {% csrf_token %}
                        <button class="btn btn-outline-warning ">Submit</button>
                    </form>

                    {% endif %}
                    {% endif %}
                </div>
                <div class="row">
                    <div class="col p-5">
                        <hr class="text-warning">
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock content %}

templates/post_update.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-info text-center">Edit Post</h2>

<div class="col-md-8 mx-auto text-center d-flex justify-content-center">

    <form class="p-3 col-md-8 card bg-secondary text-info border-white" method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form }}

        <button class="btn btn-outline-warning" type="submit" value="Save">Update</button>
    </form>
</div>

{% endblock content %}